# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/base:stable  # Choose an appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo apt-get update
      - run:
          name: Install npm
          command: sudo apt-get install -y npm
      - run:
          name: Install Dependencies
          command: |
              npm install --save-dev -y \
                "@babel/core@^7.23.2" \
                "@babel/preset-env@^7.23.2" \
                "@babel/preset-modules@^0.1.6" \
                "babel-jest@^29.7.0" \
                "cross-env@^7.0.3" \
                "jest@^27.0.6" \
                "nodemon@^3.0.1" \
                "terser-webpack-plugin@^5.3.9" \
                "webpack@^5.89.0" \
                "webpack-cli@^5.1.4"
      - run:
          name: npx jest Test
          command: npx jest

  link-check:
    docker:
      - image: cimg/node:14.0  # Choose an appropriate Node.js version
    steps:
      - checkout
      - run:
          name: Update npm
          command: sudo apt-get update
      - run:
          name: Install npm
          command: sudo apt-get install -y npm
      - run:
          name: Install Link Checker
          command: sudo npm install -g broken-link-checker-local 
      - run:
          command: pwd && find -name "index.html"
      - run:
          name: Check Links
          command: blcl -ro /src

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  tests:
    jobs:
      - build
  link-checker:
    jobs:
      - link-check